# TCL File Generated by Component Editor 11.0
# Sun Dec 04 21:36:14 EST 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | sonic_rp_ep_top "sonic_rp_ep_top" v1.0
# | Han Wang 2011.12.04.21:36:14
# | 
# | 
# | /home/hwang/sonic/projects/sonic_fpga_bugfix/pcie-refactor/testsuite/mg_sim/sonic_rp_ep/sonic_fast_sim_top.sv
# | 
# |    ./sonic_fast_sim_top.sv syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module sonic_rp_ep_top
# | 
set_module_property NAME sonic_rp_ep_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Han Wang"
set_module_property DISPLAY_NAME sonic_rp_ep_top
set_module_property TOP_LEVEL_HDL_FILE sonic_fast_sim_top.sv
set_module_property TOP_LEVEL_HDL_MODULE sonic_fast_sim_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ""
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file sonic_fast_sim_top.sv {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point pld_clk
# | 
add_interface pld_clk clock end
set_interface_property pld_clk clockRate 0

set_interface_property pld_clk ENABLED true

add_interface_port pld_clk pld_clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point rstn
# | 
add_interface rstn reset end
set_interface_property rstn associatedClock pld_clk
set_interface_property rstn synchronousEdges DEASSERT

set_interface_property rstn ENABLED true

add_interface_port rstn rstn reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point rx_clkout
# | 
add_interface rx_clkout clock end
set_interface_property rx_clkout clockRate 0

set_interface_property rx_clkout ENABLED true

add_interface_port rx_clkout xcvr_rx_clkout clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point tx_clkout
# | 
add_interface tx_clkout clock end
set_interface_property tx_clkout clockRate 0

set_interface_property tx_clkout ENABLED true

add_interface_port tx_clkout xcvr_tx_clkout clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point tx_datain
# | 
add_interface tx_datain avalon_streaming start
set_interface_property tx_datain associatedClock tx_clkout
set_interface_property tx_datain associatedReset rstn
set_interface_property tx_datain dataBitsPerSymbol 40
set_interface_property tx_datain errorDescriptor ""
set_interface_property tx_datain firstSymbolInHighOrderBits true
set_interface_property tx_datain maxChannel 0
set_interface_property tx_datain readyLatency 0

set_interface_property tx_datain ENABLED true

add_interface_port tx_datain xcvr_tx_datain data Output 40
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point rx_dataout
# | 
add_interface rx_dataout avalon_streaming end
set_interface_property rx_dataout associatedClock rx_clkout
set_interface_property rx_dataout associatedReset rstn
set_interface_property rx_dataout dataBitsPerSymbol 40
set_interface_property rx_dataout errorDescriptor ""
set_interface_property rx_dataout firstSymbolInHighOrderBits true
set_interface_property rx_dataout maxChannel 0
set_interface_property rx_dataout readyLatency 0

set_interface_property rx_dataout ENABLED true

add_interface_port rx_dataout xcvr_rx_dataout data Input 40
# | 
# +-----------------------------------
