#######################################################################
# The msim_setup.tcl script is generated
# by "Run as Modelsim" in eclipse_nios2
# 
# Here we modified the generated script to fix the following errors
# - path error for onchip_ram.hex and onchip_ram.ver
# - use the /testcode/* in this directory.
# -
#
# The best way to run debugging is through the eclipse_nios32, that way,
# we always guarantee that the code is properly compiled before simulation.
#######################################################################

all: 
	vsim -gui -do msim_setup.tcl
cmd: 
	vsim -c -do msim_setup.tcl
clean:
	rm -r work
