# TCL File Generated by Component Editor 11.0
# Wed Jul 13 10:35:41 EDT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | sonic_application_top "sonic_application_top" v1.0
# | null 2011.07.13.10:35:41
# | 
# | 
# | /home/hwang/sonic/projects/sonic_v1_11/src/sonic_app/sonic_application_top.sv
# | 
# |    ./sonic_application_top.sv syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module sonic_application_top
# | 
set_module_property NAME sonic_application_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME sonic_application_top
set_module_property TOP_LEVEL_HDL_FILE sonic_application_top.sv
set_module_property TOP_LEVEL_HDL_MODULE sonic_application_top
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ""
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file sonic_application_top.sv {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clk
# | 
add_interface clk clock end
set_interface_property clk clockRate 250000000

set_interface_property clk ENABLED true

add_interface_port clk clk_in clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point legacy_irq
# | 
add_interface legacy_irq conduit end

set_interface_property legacy_irq ENABLED true

add_interface_port legacy_irq app_int_ack export Input 1
add_interface_port legacy_irq app_int_sts export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point msi_irq
# | 
add_interface msi_irq conduit end

set_interface_property msi_irq ENABLED true

add_interface_port msi_irq app_msi_ack export Input 1
add_interface_port msi_irq app_msi_num export Output 5
add_interface_port msi_irq app_msi_req export Output 1
add_interface_port msi_irq app_msi_tc export Output 3
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point err_desc
# | 
add_interface err_desc conduit end

set_interface_property err_desc ENABLED true

add_interface_port err_desc err_desc export Output 128
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point pex_msi_num
# | 
add_interface pex_msi_num conduit end

set_interface_property pex_msi_num ENABLED true

add_interface_port pex_msi_num pex_msi_num export Output 5
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point rx_st
# | 
add_interface rx_st avalon_streaming end
set_interface_property rx_st associatedClock clk
set_interface_property rx_st associatedReset reset_n
set_interface_property rx_st dataBitsPerSymbol 128
set_interface_property rx_st errorDescriptor ""
set_interface_property rx_st firstSymbolInHighOrderBits true
set_interface_property rx_st maxChannel 0
set_interface_property rx_st readyLatency 0

set_interface_property rx_st ENABLED true

add_interface_port rx_st rx_st_data0 data Input 128
add_interface_port rx_st rx_st_empty0 empty Input 1
add_interface_port rx_st rx_st_eop0 endofpacket Input 1
add_interface_port rx_st rx_st_err0 error Input 1
add_interface_port rx_st rx_st_sop0 startofpacket Input 1
add_interface_port rx_st rx_st_valid0 valid Input 1
add_interface_port rx_st rx_st_ready0 ready Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point tx_st
# | 
add_interface tx_st avalon_streaming start
set_interface_property tx_st associatedClock clk
set_interface_property tx_st associatedReset reset_n
set_interface_property tx_st dataBitsPerSymbol 128
set_interface_property tx_st errorDescriptor ""
set_interface_property tx_st firstSymbolInHighOrderBits true
set_interface_property tx_st maxChannel 0
set_interface_property tx_st readyLatency 0

set_interface_property tx_st ENABLED true

add_interface_port tx_st tx_st_data0 data Output 128
add_interface_port tx_st tx_st_empty0 empty Output 1
add_interface_port tx_st tx_st_eop0 endofpacket Output 1
add_interface_port tx_st tx_st_err0 error Output 1
add_interface_port tx_st tx_st_ready0 ready Input 1
add_interface_port tx_st tx_st_sop0 startofpacket Output 1
add_interface_port tx_st tx_st_valid0 valid Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point rx_st_component_specific
# | 
add_interface rx_st_component_specific conduit end

set_interface_property rx_st_component_specific ENABLED true

add_interface_port rx_st_component_specific rx_st_bardec0 export Input 8
add_interface_port rx_st_component_specific rx_st_be0 export Input 16
add_interface_port rx_st_component_specific rx_stream_mask0 export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point cpl_err
# | 
add_interface cpl_err conduit end

set_interface_property cpl_err ENABLED true

add_interface_port cpl_err cpl_err export Output 7
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point cpl_pending
# | 
add_interface cpl_pending conduit end

set_interface_property cpl_pending ENABLED true

add_interface_port cpl_pending cpl_pending export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point tl_cfg_app_interface
# | 
add_interface tl_cfg_app_interface conduit end

set_interface_property tl_cfg_app_interface ENABLED true

add_interface_port tl_cfg_app_interface cfg_busdev export Input 13
add_interface_port tl_cfg_app_interface cfg_devcsr export Input 32
add_interface_port tl_cfg_app_interface cfg_msicsr export Input 16
add_interface_port tl_cfg_app_interface cfg_prmcsr export Input 32
add_interface_port tl_cfg_app_interface cfg_tcvcmap export Input 24
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point tx_stream_cred0
# | 
add_interface tx_stream_cred0 conduit end

set_interface_property tx_stream_cred0 ENABLED true

add_interface_port tx_stream_cred0 tx_stream_cred0 export Input 36
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point tx_stream_fifo_empty
# | 
add_interface tx_stream_fifo_empty conduit end

set_interface_property tx_stream_fifo_empty ENABLED true

add_interface_port tx_stream_fifo_empty tx_stream_fifo_empty0 export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point xcvr_rx_clkout
# | 
add_interface xcvr_rx_clkout clock end
set_interface_property xcvr_rx_clkout clockRate 257812500

set_interface_property xcvr_rx_clkout ENABLED true

add_interface_port xcvr_rx_clkout xcvr_rx_clkout clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point xcvr_tx_clkout
# | 
add_interface xcvr_tx_clkout clock end
set_interface_property xcvr_tx_clkout clockRate 257812500

set_interface_property xcvr_tx_clkout ENABLED true

add_interface_port xcvr_tx_clkout xcvr_tx_clkout clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point cfg_linkcsr
# | 
add_interface cfg_linkcsr conduit end

set_interface_property cfg_linkcsr ENABLED true

add_interface_port cfg_linkcsr cfg_linkcsr export Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point gen2_speed
# | 
add_interface gen2_speed conduit end

set_interface_property gen2_speed ENABLED true

add_interface_port gen2_speed gen2_speed export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point xcvr_rx_dataout
# | 
add_interface xcvr_rx_dataout conduit end

set_interface_property xcvr_rx_dataout ENABLED true

add_interface_port xcvr_rx_dataout xcvr_rx_dataout export Input 40
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point xcvr_tx_datain
# | 
add_interface xcvr_tx_datain conduit end

set_interface_property xcvr_tx_datain ENABLED true

add_interface_port xcvr_tx_datain xcvr_tx_datain export Output 40
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_n
# | 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clk
set_interface_property reset_n synchronousEdges DEASSERT

set_interface_property reset_n ENABLED true

add_interface_port reset_n rstn reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point pma_tx_ready
# | 
add_interface pma_tx_ready conduit end

set_interface_property pma_tx_ready ENABLED true

add_interface_port pma_tx_ready pma_tx_ready export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point pma_rx_ready
# | 
add_interface pma_rx_ready conduit end

set_interface_property pma_rx_ready ENABLED true

add_interface_port pma_rx_ready pma_rx_ready export Input 1
# | 
# +-----------------------------------
