# TCL File Generated by Component Editor 11.0
# Sun Aug 21 14:34:26 EDT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | avalon_slave "avalon_slave" v2.0
# | Han Wang 2011.08.21.14:34:26
# | Parameterizable input/output component with an Avalon-MM slave port
# | 
# | /home/hwang/sonic/projects/sonic_fpga/src/top_examples/misc/avalon_mm_slave/avalon_mm_slave.v
# | 
# |    ./avalon_mm_slave.v syn, sim
# |    ./interrupt_logic.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module avalon_slave
# | 
set_module_property DESCRIPTION "Parameterizable input/output component with an Avalon-MM slave port"
set_module_property NAME avalon_slave
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Templates
set_module_property AUTHOR "Han Wang"
set_module_property DISPLAY_NAME avalon_slave
set_module_property TOP_LEVEL_HDL_FILE avalon_mm_slave.v
set_module_property TOP_LEVEL_HDL_MODULE avalon_mm_slave
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME "avalon_mm_slave"
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file avalon_mm_slave.v {SYNTHESIS SIMULATION}
add_file interrupt_logic.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter DATA_WIDTH INTEGER 32 "Width of each input or output"
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME "Word Size"
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES {8 16 32}
set_parameter_property DATA_WIDTH DESCRIPTION "Width of each input or output"
set_parameter_property DATA_WIDTH AFFECTS_GENERATION false
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter ENABLE_SYNC_SIGNALS INTEGER 0 "Output syncronization signals"
set_parameter_property ENABLE_SYNC_SIGNALS DEFAULT_VALUE 0
set_parameter_property ENABLE_SYNC_SIGNALS DISPLAY_NAME "Syncronization signals"
set_parameter_property ENABLE_SYNC_SIGNALS TYPE INTEGER
set_parameter_property ENABLE_SYNC_SIGNALS UNITS None
set_parameter_property ENABLE_SYNC_SIGNALS ALLOWED_RANGES {0:Disabled 1:Enabled}
set_parameter_property ENABLE_SYNC_SIGNALS DESCRIPTION "Output syncronization signals"
set_parameter_property ENABLE_SYNC_SIGNALS AFFECTS_GENERATION false
set_parameter_property ENABLE_SYNC_SIGNALS HDL_PARAMETER true
add_parameter MODE_0 INTEGER 2 "Set the read/write capabilites of the register pair 0"
set_parameter_property MODE_0 DEFAULT_VALUE 2
set_parameter_property MODE_0 DISPLAY_NAME "Register 0 capabilites"
set_parameter_property MODE_0 TYPE INTEGER
set_parameter_property MODE_0 UNITS None
set_parameter_property MODE_0 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_0 DESCRIPTION "Set the read/write capabilites of the register pair 0"
set_parameter_property MODE_0 AFFECTS_GENERATION false
set_parameter_property MODE_0 HDL_PARAMETER true
add_parameter MODE_1 INTEGER 4 "Set the read/write capabilites of the register pair 1"
set_parameter_property MODE_1 DEFAULT_VALUE 4
set_parameter_property MODE_1 DISPLAY_NAME "Register 1 capabilites"
set_parameter_property MODE_1 TYPE INTEGER
set_parameter_property MODE_1 UNITS None
set_parameter_property MODE_1 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_1 DESCRIPTION "Set the read/write capabilites of the register pair 1"
set_parameter_property MODE_1 AFFECTS_GENERATION false
set_parameter_property MODE_1 HDL_PARAMETER true
add_parameter MODE_2 INTEGER 4 "Set the read/write capabilites of the register pair 2"
set_parameter_property MODE_2 DEFAULT_VALUE 4
set_parameter_property MODE_2 DISPLAY_NAME "Register 2 capabilites"
set_parameter_property MODE_2 TYPE INTEGER
set_parameter_property MODE_2 UNITS None
set_parameter_property MODE_2 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_2 DESCRIPTION "Set the read/write capabilites of the register pair 2"
set_parameter_property MODE_2 AFFECTS_GENERATION false
set_parameter_property MODE_2 HDL_PARAMETER true
add_parameter MODE_3 INTEGER 4 "Set the read/write capabilites of the register pair 3"
set_parameter_property MODE_3 DEFAULT_VALUE 4
set_parameter_property MODE_3 DISPLAY_NAME "Register 3 capabilites"
set_parameter_property MODE_3 TYPE INTEGER
set_parameter_property MODE_3 UNITS None
set_parameter_property MODE_3 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_3 DESCRIPTION "Set the read/write capabilites of the register pair 3"
set_parameter_property MODE_3 AFFECTS_GENERATION false
set_parameter_property MODE_3 HDL_PARAMETER true
add_parameter MODE_4 INTEGER 4 "Set the read/write capabilites of the register pair 4"
set_parameter_property MODE_4 DEFAULT_VALUE 4
set_parameter_property MODE_4 DISPLAY_NAME "Register 4 capabilites"
set_parameter_property MODE_4 TYPE INTEGER
set_parameter_property MODE_4 UNITS None
set_parameter_property MODE_4 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_4 DESCRIPTION "Set the read/write capabilites of the register pair 4"
set_parameter_property MODE_4 AFFECTS_GENERATION false
set_parameter_property MODE_4 HDL_PARAMETER true
add_parameter MODE_5 INTEGER 4 "Set the read/write capabilites of the register pair 5"
set_parameter_property MODE_5 DEFAULT_VALUE 4
set_parameter_property MODE_5 DISPLAY_NAME "Register 5 capabilites"
set_parameter_property MODE_5 TYPE INTEGER
set_parameter_property MODE_5 UNITS None
set_parameter_property MODE_5 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_5 DESCRIPTION "Set the read/write capabilites of the register pair 5"
set_parameter_property MODE_5 AFFECTS_GENERATION false
set_parameter_property MODE_5 HDL_PARAMETER true
add_parameter MODE_6 INTEGER 4 "Set the read/write capabilites of the register pair 6"
set_parameter_property MODE_6 DEFAULT_VALUE 4
set_parameter_property MODE_6 DISPLAY_NAME "Register 6 capabilites"
set_parameter_property MODE_6 TYPE INTEGER
set_parameter_property MODE_6 UNITS None
set_parameter_property MODE_6 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_6 DESCRIPTION "Set the read/write capabilites of the register pair 6"
set_parameter_property MODE_6 AFFECTS_GENERATION false
set_parameter_property MODE_6 HDL_PARAMETER true
add_parameter MODE_7 INTEGER 4 "Set the read/write capabilites of the register pair 7"
set_parameter_property MODE_7 DEFAULT_VALUE 4
set_parameter_property MODE_7 DISPLAY_NAME "Register 7 capabilites"
set_parameter_property MODE_7 TYPE INTEGER
set_parameter_property MODE_7 UNITS None
set_parameter_property MODE_7 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_7 DESCRIPTION "Set the read/write capabilites of the register pair 7"
set_parameter_property MODE_7 AFFECTS_GENERATION false
set_parameter_property MODE_7 HDL_PARAMETER true
add_parameter MODE_8 INTEGER 4 "Set the read/write capabilites of the register pair 8"
set_parameter_property MODE_8 DEFAULT_VALUE 4
set_parameter_property MODE_8 DISPLAY_NAME "Register 8 capabilites"
set_parameter_property MODE_8 TYPE INTEGER
set_parameter_property MODE_8 UNITS None
set_parameter_property MODE_8 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_8 DESCRIPTION "Set the read/write capabilites of the register pair 8"
set_parameter_property MODE_8 AFFECTS_GENERATION false
set_parameter_property MODE_8 HDL_PARAMETER true
add_parameter MODE_9 INTEGER 4 "Set the read/write capabilites of the register pair 9"
set_parameter_property MODE_9 DEFAULT_VALUE 4
set_parameter_property MODE_9 DISPLAY_NAME "Register 9 capabilites"
set_parameter_property MODE_9 TYPE INTEGER
set_parameter_property MODE_9 UNITS None
set_parameter_property MODE_9 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_9 DESCRIPTION "Set the read/write capabilites of the register pair 9"
set_parameter_property MODE_9 AFFECTS_GENERATION false
set_parameter_property MODE_9 HDL_PARAMETER true
add_parameter MODE_10 INTEGER 4 "Set the read/write capabilites of the register pair 10"
set_parameter_property MODE_10 DEFAULT_VALUE 4
set_parameter_property MODE_10 DISPLAY_NAME "Register 10 capabilites"
set_parameter_property MODE_10 TYPE INTEGER
set_parameter_property MODE_10 UNITS None
set_parameter_property MODE_10 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_10 DESCRIPTION "Set the read/write capabilites of the register pair 10"
set_parameter_property MODE_10 AFFECTS_GENERATION false
set_parameter_property MODE_10 HDL_PARAMETER true
add_parameter MODE_11 INTEGER 4 "Set the read/write capabilites of the register pair 11"
set_parameter_property MODE_11 DEFAULT_VALUE 4
set_parameter_property MODE_11 DISPLAY_NAME "Register 11 capabilites"
set_parameter_property MODE_11 TYPE INTEGER
set_parameter_property MODE_11 UNITS None
set_parameter_property MODE_11 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_11 DESCRIPTION "Set the read/write capabilites of the register pair 11"
set_parameter_property MODE_11 AFFECTS_GENERATION false
set_parameter_property MODE_11 HDL_PARAMETER true
add_parameter MODE_12 INTEGER 4 "Set the read/write capabilites of the register pair 12"
set_parameter_property MODE_12 DEFAULT_VALUE 4
set_parameter_property MODE_12 DISPLAY_NAME "Register 12 capabilites"
set_parameter_property MODE_12 TYPE INTEGER
set_parameter_property MODE_12 UNITS None
set_parameter_property MODE_12 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_12 DESCRIPTION "Set the read/write capabilites of the register pair 12"
set_parameter_property MODE_12 AFFECTS_GENERATION false
set_parameter_property MODE_12 HDL_PARAMETER true
add_parameter MODE_13 INTEGER 4 "Set the read/write capabilites of the register pair 13"
set_parameter_property MODE_13 DEFAULT_VALUE 4
set_parameter_property MODE_13 DISPLAY_NAME "Register 13 capabilites"
set_parameter_property MODE_13 TYPE INTEGER
set_parameter_property MODE_13 UNITS None
set_parameter_property MODE_13 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_13 DESCRIPTION "Set the read/write capabilites of the register pair 13"
set_parameter_property MODE_13 AFFECTS_GENERATION false
set_parameter_property MODE_13 HDL_PARAMETER true
add_parameter MODE_14 INTEGER 4 "Set the read/write capabilites of the register pair 14"
set_parameter_property MODE_14 DEFAULT_VALUE 4
set_parameter_property MODE_14 DISPLAY_NAME "Register 14 capabilites"
set_parameter_property MODE_14 TYPE INTEGER
set_parameter_property MODE_14 UNITS None
set_parameter_property MODE_14 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_14 DESCRIPTION "Set the read/write capabilites of the register pair 14"
set_parameter_property MODE_14 AFFECTS_GENERATION false
set_parameter_property MODE_14 HDL_PARAMETER true
add_parameter MODE_15 INTEGER 4 "Set the read/write capabilites of the register pair 15"
set_parameter_property MODE_15 DEFAULT_VALUE 4
set_parameter_property MODE_15 DISPLAY_NAME "Register 15 capabilites"
set_parameter_property MODE_15 TYPE INTEGER
set_parameter_property MODE_15 UNITS None
set_parameter_property MODE_15 ALLOWED_RANGES {"0:Write Only" "1:Read Only" 2:Write/Read "3:Write with Loopback" 4:Disabled}
set_parameter_property MODE_15 DESCRIPTION "Set the read/write capabilites of the register pair 15"
set_parameter_property MODE_15 AFFECTS_GENERATION false
set_parameter_property MODE_15 HDL_PARAMETER true
add_parameter IRQ_EN INTEGER 1 "Enable or disable the interrupt capabilities of input ports"
set_parameter_property IRQ_EN DEFAULT_VALUE 1
set_parameter_property IRQ_EN DISPLAY_NAME "Interrupt capabilities"
set_parameter_property IRQ_EN TYPE INTEGER
set_parameter_property IRQ_EN UNITS None
set_parameter_property IRQ_EN ALLOWED_RANGES {0:Enabled 1:Disabled}
set_parameter_property IRQ_EN DESCRIPTION "Enable or disable the interrupt capabilities of input ports"
set_parameter_property IRQ_EN AFFECTS_GENERATION false
set_parameter_property IRQ_EN HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges DEASSERT

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point s0
# | 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset clock_reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 readLatency 3
set_interface_property s0 readWaitStates 0
set_interface_property s0 readWaitTime 0
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0

set_interface_property s0 ENABLED true

add_interface_port s0 slave_address address Input 9
add_interface_port s0 slave_read read Input 1
add_interface_port s0 slave_write write Input 1
add_interface_port s0 slave_readdata readdata Output 32
add_interface_port s0 slave_writedata writedata Input 32
add_interface_port s0 slave_byteenable byteenable Input DATA_WIDTH/8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point slv_irq
# | 
add_interface slv_irq interrupt end
set_interface_property slv_irq associatedAddressablePoint s0
set_interface_property slv_irq associatedClock clock
set_interface_property slv_irq associatedReset clock_reset

set_interface_property slv_irq ENABLED true

add_interface_port slv_irq slave_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point user_interface
# | 
add_interface user_interface conduit end

set_interface_property user_interface ENABLED true

add_interface_port user_interface user_dataout_0 export Output DATA_WIDTH
add_interface_port user_interface user_dataout_1 export Output DATA_WIDTH
add_interface_port user_interface user_dataout_2 export Output DATA_WIDTH
add_interface_port user_interface user_dataout_3 export Output DATA_WIDTH
add_interface_port user_interface user_dataout_4 export Output DATA_WIDTH
add_interface_port user_interface user_dataout_5 export Output DATA_WIDTH
add_interface_port user_interface user_dataout_6 export Output DATA_WIDTH
add_interface_port user_interface user_dataout_7 export Output DATA_WIDTH
add_interface_port user_interface user_dataout_8 export Output DATA_WIDTH
add_interface_port user_interface user_dataout_9 export Output DATA_WIDTH
add_interface_port user_interface user_dataout_10 export Output DATA_WIDTH
add_interface_port user_interface user_dataout_11 export Output DATA_WIDTH
add_interface_port user_interface user_dataout_12 export Output DATA_WIDTH
add_interface_port user_interface user_dataout_13 export Output DATA_WIDTH
add_interface_port user_interface user_dataout_14 export Output DATA_WIDTH
add_interface_port user_interface user_dataout_15 export Output DATA_WIDTH
add_interface_port user_interface user_datain_0 export Input DATA_WIDTH
add_interface_port user_interface user_datain_1 export Input DATA_WIDTH
add_interface_port user_interface user_datain_2 export Input DATA_WIDTH
add_interface_port user_interface user_datain_3 export Input DATA_WIDTH
add_interface_port user_interface user_datain_4 export Input DATA_WIDTH
add_interface_port user_interface user_datain_5 export Input DATA_WIDTH
add_interface_port user_interface user_datain_6 export Input DATA_WIDTH
add_interface_port user_interface user_datain_7 export Input DATA_WIDTH
add_interface_port user_interface user_datain_8 export Input DATA_WIDTH
add_interface_port user_interface user_datain_9 export Input DATA_WIDTH
add_interface_port user_interface user_datain_10 export Input DATA_WIDTH
add_interface_port user_interface user_datain_11 export Input DATA_WIDTH
add_interface_port user_interface user_datain_12 export Input DATA_WIDTH
add_interface_port user_interface user_datain_13 export Input DATA_WIDTH
add_interface_port user_interface user_datain_14 export Input DATA_WIDTH
add_interface_port user_interface user_datain_15 export Input DATA_WIDTH
add_interface_port user_interface user_write export Output 1
add_interface_port user_interface user_read export Output 1
add_interface_port user_interface user_chipselect export Output 16
add_interface_port user_interface user_byteenable export Output DATA_WIDTH/8
# | 
# +-----------------------------------
