# TCL File Generated by Component Editor 11.0
# Thu Jan 05 01:11:17 EST 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | sonic_vc_demultiplexer_custom "sonic_vc_demultiplexer_custom" v1.0
# | null 2012.01.05.01:11:17
# | 
# | 
# | /home/hwang/sonic/projects/sonic_fpga_bugfix/pcie-refactor-debug-port1/cmdctrl/lib/sonic/vc/sonic_vc_demultiplexer_custom.sv
# | 
# |    ./sonic_vc_demultiplexer_custom.sv syn
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module sonic_vc_demultiplexer_custom
# | 
set_module_property NAME sonic_vc_demultiplexer_custom
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME sonic_vc_demultiplexer_custom
set_module_property TOP_LEVEL_HDL_FILE sonic_vc_demultiplexer_custom.sv
set_module_property TOP_LEVEL_HDL_MODULE sonic_vc_demultiplexer_0
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME sonic_vc_demultiplexer_0
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file sonic_vc_demultiplexer_custom.sv SYNTHESIS
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 250000000

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point in
# | 
add_interface in avalon_streaming end
set_interface_property in associatedClock clock
set_interface_property in associatedReset reset_n
set_interface_property in dataBitsPerSymbol 64
set_interface_property in errorDescriptor ""
set_interface_property in firstSymbolInHighOrderBits true
set_interface_property in maxChannel 1
set_interface_property in readyLatency 2

set_interface_property in ENABLED true

add_interface_port in in_valid valid Input 1
add_interface_port in in_ready ready Output 1
add_interface_port in in_data data Input 128
add_interface_port in in_startofpacket startofpacket Input 1
add_interface_port in in_endofpacket endofpacket Input 1
add_interface_port in in_empty empty Input 1
add_interface_port in in_channel channel Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point out0
# | 
add_interface out0 avalon_streaming start
set_interface_property out0 associatedClock clock
set_interface_property out0 associatedReset reset_n
set_interface_property out0 dataBitsPerSymbol 64
set_interface_property out0 errorDescriptor ""
set_interface_property out0 firstSymbolInHighOrderBits true
set_interface_property out0 maxChannel 0
set_interface_property out0 readyLatency 2

set_interface_property out0 ENABLED true

add_interface_port out0 out0_valid valid Output 1
add_interface_port out0 out0_ready ready Input 1
add_interface_port out0 out0_data data Output 128
add_interface_port out0 out0_startofpacket startofpacket Output 1
add_interface_port out0 out0_endofpacket endofpacket Output 1
add_interface_port out0 out0_empty empty Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point out1
# | 
add_interface out1 avalon_streaming start
set_interface_property out1 associatedClock clock
set_interface_property out1 associatedReset reset_n
set_interface_property out1 dataBitsPerSymbol 64
set_interface_property out1 errorDescriptor ""
set_interface_property out1 firstSymbolInHighOrderBits true
set_interface_property out1 maxChannel 0
set_interface_property out1 readyLatency 2

set_interface_property out1 ENABLED true

add_interface_port out1 out1_valid valid Output 1
add_interface_port out1 out1_ready ready Input 1
add_interface_port out1 out1_data data Output 128
add_interface_port out1 out1_startofpacket startofpacket Output 1
add_interface_port out1 out1_endofpacket endofpacket Output 1
add_interface_port out1 out1_empty empty Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point in_bardec
# | 
add_interface in_bardec conduit end

set_interface_property in_bardec ENABLED true

add_interface_port in_bardec in_bardec export Input 8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point in_be
# | 
add_interface in_be conduit end

set_interface_property in_be ENABLED true

add_interface_port in_be in_be export Input 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point out0_bardec
# | 
add_interface out0_bardec conduit end

set_interface_property out0_bardec ENABLED true

add_interface_port out0_bardec out0_bardec export Output 8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point out0_be
# | 
add_interface out0_be conduit end

set_interface_property out0_be ENABLED true

add_interface_port out0_be out0_be export Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point out1_bardec
# | 
add_interface out1_bardec conduit end

set_interface_property out1_bardec ENABLED true

add_interface_port out1_bardec out1_bardec export Output 8
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point out1_be
# | 
add_interface out1_be conduit end

set_interface_property out1_be ENABLED true

add_interface_port out1_be out1_be export Output 16
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset_n
# | 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clock
set_interface_property reset_n synchronousEdges DEASSERT

set_interface_property reset_n ENABLED true

add_interface_port reset_n reset_n reset_n Input 1
# | 
# +-----------------------------------
