# TCL File Generated by Component Editor 10.1
# Sun May 29 20:59:44 EDT 2011
# DO NOT MODIFY


# +-----------------------------------
# | 
# | eth_10g_mon "10GE Packet Monitor" v1.0
# |  2011.05.29.20:59:44
# | 10GE Packet Monitor
# | 
# | /home/hwang/sandbox/altera_eth_10g_design_example/altera_eth_10g_mac_base_r/eth_10g_mon.v
# | 
# |    ./eth_10g_mon.v syn, sim
# |    ./crcchk.vo sim
# |    ./crcchk.v syn
# |    ./crcchk_altcrc.v syn
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module eth_10g_mon
# | 
set_module_property DESCRIPTION "10GE Packet Monitor"
set_module_property NAME eth_10g_mon
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Interface Protocols/Ethernet"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "10GE Packet Monitor"
set_module_property TOP_LEVEL_HDL_FILE eth_10g_mon.v
set_module_property TOP_LEVEL_HDL_MODULE eth_10g_mon
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file eth_10g_mon.v {SYNTHESIS SIMULATION}
add_file crcchk.vo SIMULATION
add_file crcchk.v SYNTHESIS
add_file crcchk_altcrc.v SYNTHESIS
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges DEASSERT

set_interface_property clock_reset ENABLED true

add_interface_port clock_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset clock_reset
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 address address Input 3
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_streaming_sink
# | 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock
set_interface_property avalon_streaming_sink associatedReset clock_reset
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 1
set_interface_property avalon_streaming_sink symbolsPerBeat 8

set_interface_property avalon_streaming_sink ENABLED true

add_interface_port avalon_streaming_sink rx_data data Input 64
add_interface_port avalon_streaming_sink rx_valid valid Input 1
add_interface_port avalon_streaming_sink rx_sop startofpacket Input 1
add_interface_port avalon_streaming_sink rx_eop endofpacket Input 1
add_interface_port avalon_streaming_sink rx_empty empty Input 3
add_interface_port avalon_streaming_sink rx_error error Input 6
add_interface_port avalon_streaming_sink rx_ready ready Output 1
# | 
# +-----------------------------------
